# Generated by Django 3.1.6 on 2021-02-15 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('abstract', models.CharField(max_length=1000, unique=True)),
                ('reviewed', models.BooleanField()),
                ('date_added', models.DateField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_tool_app.language')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_published', models.DateField(default='1000')),
                ('convention_published', models.CharField(max_length=300)),
                ('convention_venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('papers', models.ManyToManyField(to='search_tool_app.Papers')),
            ],
        ),
        migrations.CreateModel(
            name='PaperUsedMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_used', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_tool_app.materials')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_tool_app.papers')),
            ],
        ),
        migrations.AddField(
            model_name='papers',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_tool_app.type'),
        ),
        migrations.AddField(
            model_name='papers',
            name='year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_tool_app.year'),
        ),
        migrations.AddField(
            model_name='materials',
            name='papers_id',
            field=models.ManyToManyField(through='search_tool_app.PaperUsedMaterial', to='search_tool_app.Papers'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('country_of_origin', models.CharField(max_length=300)),
                ('paper', models.ManyToManyField(to='search_tool_app.Papers')),
            ],
        ),
    ]
