# Generated by Django 3.1.6 on 2022-04-16 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('country_of_origin', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, default='no-slug')),
                ('pdf', models.FileField(null=True, upload_to='papers/pdfs')),
                ('abstract', models.TextField(max_length=3000, null=True, unique=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('date_added', models.DateField(default=datetime.date.today, null=True)),
                ('author', models.ManyToManyField(to='search_tool_app.Author')),
                ('language', models.ManyToManyField(to='search_tool_app.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_published', models.DateField(default='1000')),
                ('convention_published', models.CharField(max_length=300)),
                ('convention_venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaperUsedMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_used', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_tool_app.material')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_tool_app.paper')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='material',
            field=models.ManyToManyField(through='search_tool_app.PaperUsedMaterial', to='search_tool_app.Material'),
        ),
        migrations.AddField(
            model_name='paper',
            name='tag',
            field=models.ManyToManyField(to='search_tool_app.Tag'),
        ),
        migrations.AddField(
            model_name='paper',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_tool_app.type'),
        ),
        migrations.AddField(
            model_name='paper',
            name='year_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_tool_app.year'),
        ),
    ]
