# Generated by Django 3.1.6 on 2021-02-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_tool_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materials',
            new_name='Material',
        ),
        migrations.RenameModel(
            old_name='Papers',
            new_name='Paper',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
