# Generated by Django 3.1.6 on 2021-02-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_tool_app', '0002_auto_20210216_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='date_added',
            field=models.DateField(blank=True),
        ),
    ]
