# Generated by Django 3.1.6 on 2021-02-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_tool_app', '0003_auto_20210216_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='date_added',
            field=models.DateField(),
        ),
    ]
