# Generated by Django 3.1.6 on 2021-02-18 18:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_tool_app', '0005_auto_20210216_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='date_added',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_tool_app.language'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='reviewed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_tool_app.type'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_tool_app.year'),
        ),
    ]
