# Generated by Django 3.1.6 on 2022-09-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_tool_app', '0005_auto_20220706_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
