# Generated by Django 3.1.6 on 2021-02-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_tool_app', '0006_auto_20210218_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='papers_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='papers',
        ),
        migrations.AddField(
            model_name='paper',
            name='material',
            field=models.ManyToManyField(through='search_tool_app.PaperUsedMaterial', to='search_tool_app.Material'),
        ),
        migrations.AddField(
            model_name='paper',
            name='tag',
            field=models.ManyToManyField(to='search_tool_app.Tag'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
