# Generated by Django 3.1.6 on 2021-02-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_tool_app', '0007_auto_20210218_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='paper',
            field=models.ManyToManyField(blank=True, to='search_tool_app.Paper'),
        ),
        migrations.RemoveField(
            model_name='paper',
            name='language',
        ),
        migrations.AddField(
            model_name='paper',
            name='language',
            field=models.ManyToManyField(to='search_tool_app.Language'),
        ),
    ]
