# Generated by Django 3.1.6 on 2021-05-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_tool_app', '0009_auto_20210309_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='slug',
            field=models.SlugField(default='no-slug'),
        ),
    ]
