# Generated by Django 3.1.6 on 2021-06-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_tool_app', '0010_paper_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(max_length=3000, null=True, unique=True),
        ),
    ]
