# Generated by Django 3.1.6 on 2021-06-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_tool_app', '0011_auto_20210623_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='slug',
            field=models.SlugField(blank=True, default='no-slug'),
        ),
    ]
