# Generated by Django 3.1.6 on 2022-01-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_tool_app', '0012_auto_20210625_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='paper',
        ),
        migrations.AddField(
            model_name='paper',
            name='author',
            field=models.ManyToManyField(to='search_tool_app.Author'),
        ),
    ]
