# Generated by Django 3.1.6 on 2022-01-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_tool_app', '0013_auto_20220107_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='surname',
        ),
    ]
